### ISSUE TITLE
Implementation of the exception handler in the project

### ISSUE THREAD

**Issue by PanasyukVA** [TasksManagement/TasksManagement#5]

**Comment by PanasyukVA** [comment]
To implement exception handling, please, use the following article: 
https://www.codeproject.com/articles/731913/exception-handling-in-mvc

**Comment by PanasyukVA** [comment]
I have checked results. It is necessary to hide error's stack trace to the hidden div http://prnt.sc/et26ti

**Comment by ilyaskav** [comment]
fixed, will be available in the next commit
