### ISSUE TITLE
Creation of a layout and home page

### ISSUE THREAD

**Issue by PanasyukVA** [TasksManagement/TasksManagement#6]

**Comment by IhorPashkovskyi** [comment]
accepted

**Comment by IhorPashkovskyi** [comment]
Разбиение задачи на подзадачи:

1.Создать layout (с применением собственных стилей)
   - Header
   - Footer

2.Создать главную страницу  (с применением собственных стилей)
   - Заполнение Body контентом сайта

**Comment by PanasyukVA** [comment]
Я бы включил в данную задачу изменение дефолтных стилей сайта. Чтобы сайт не выглядел шаблонным

**Comment by IhorPashkovskyi** [comment]
Понял, сделаю.

**Comment by IhorPashkovskyi** [comment]
Примерный вид главной страницы (пока на русском, переведу на английский):

Хотите создавать проекты в команде?
Тогда Вам может это понравится. Бесплатная платформа для реализации Ваших идей. Находите людей по интересам или приглашайте
знакомых и создавайте свою команду.

Разделяй, назначай, выполняй
Хороший программный продукт должен вмещать в себе четкую, понятную бизнес-логику, максимальное удобство для пользователя. Согласитесь,
что одному человеку будет тяжело в одиночку реализовать действительно хороший программный продукт. Как же решить такую проблему?
Имея команду из определенного количества единомышленноков вы можете распределить задачи между ними, выставить приоритеты, назначить
сроки, и Ваш проект начнет делать целая команда программистов (!концовка не очень нравиться, нужно будет додумать).

У меня нет идеи, я хочу помочь
Если у Вас нет идеи, то не стоит отчаеватся. Вы можете поискать на сайте проекты других людей. Когда вы найдете то, что Вам интересно,
то можете попросить админа группы пригласить Вас. Теперь Вы являетесь частью команды, и можете помогать другим.

**Comment by IhorPashkovskyi** [comment]
Сделано:

1. Установлен логотип в шапке сайта.
2. Добавленные данные в футер.
3. Создана общая структура главной старницы.

Собираюсь сегодня делать:

1. Разобратся с футером (при изменении размера старницы браузера футер ведет себя не естественно - текст начинает съезжать).
2. Додумать контент главной страницы.
3. Перевести на английский.
!4. Если успею, разьерусь с логотипом (хотел что б при наведении на значок логотипа или название сайта, они менялись). Реализовываю
это через псевдо-свойство :hover, но что-то оно не срабатывает.

!!!Соответственно буду добавлять стили чтобы контент был красивее, но это скорее всего уже на выходных, т.к. сегодня все не успею.

**Comment by IhorPashkovskyi** [comment]
Сделал:
1. Добавил favicon
2. Подредактировал шапку
3. Перевел текст на английский

Сегодня собираюсь сделать:
1. Доделаю шапку(стили для кнопок)
2. Футер(чтоб текст не съезжал)
3. Постараюсь доработать контент

**Comment by IhorPashkovskyi** [comment]
Завершил Layout и Main Page (возможны корректировки).

**Comment by IhorPashkovskyi** [comment]
Новые изменения:
полностью подправил футер (теперь он находится внизу в независимости от количества контекста на странице), изменил шрифт, убрал кнопку регистрации внизу страницы, добавил стили для кнопок регистрации и входа в хедере.
