### ISSUE TITLE
Implementation of authorization and authentication 

### ISSUE THREAD

**Issue by PanasyukVA** [TasksManagement/TasksManagement#7]

**Comment by AndrewBogach** [comment]
Настраиваю feature сброса пароля (на случай если пользователь его забыл). Нужен почтовый адрес.
Предлагаю создать общий email для нашего приложения на gmail.

**Comment by AndrewBogach** [comment]
Хочу сделать register/login на одной странице, как в gitlab. 
Для этого использовать tab-panel bootstrap. 
Пока не разобрался как использовать две модели (register и login) на одной странице.
Как это лучше сделать и стоит ли?
