### ISSUE TITLE
Implementation of roles editing 

### ISSUE THREAD

**Issue by PanasyukVA** [TasksManagement/TasksManagement#8]
- list of users
- changing roles

**Comment by AndrewBogach** [comment]
Виталик, уточни, пожалуйста, что нужно сделать в этой задаче.
В нашей БД есть таблица с ролями и типами ролей, которая заполняется при создании БД.
Мне создать страницу админа, в которой будет возможность редактировать эти таблицы.
Или роли будут меняться только в списке членов группы с помощью dropdown?

**Comment by PanasyukVA** [comment]
Требования для данной задачи можно взять прямиком с gitlab.
